# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Matt Calsada
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Developer
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://matt.calsada.org" # the base hostname & protocol for your site

permalink: /blog/:year/:month/:day/:title

# Social media profiles - feel free to add more here
twitter_username: mcal
github_username:  mcalsada
facebook_username: Matt.Calsada
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
linkedin_url: https://linkedin.com/mattcalsada/

# Address information
#address_street: 3034 Melrose Place
address_city: Virginia Beach
address_state: VA
address_zip: 23456

# Build settings
markdown: kramdown